### ISSUE TITLE
Adobe XD Einarbeitung

### ISSUE THREAD

**Issue by TeasiT** [upbracing/ventilator#2]
https://www.adobe.com/de/products/xd.html?sdid=91BF525M&mv=search&ef_id=CjwKCAjw1cX0BRBmEiwAy9tKHpoUyWW7wPAqwN-dFvjpBzTU7xNIRyTK3i8JNsPwwgLfOoBE3uQqJxoCmu4QAvD_BwE:G:s&s_kwcid=AL!3085!3!394597829420!e!!g!!adobe%20xd

**Comment by Zauberhanz** [comment]
Worked through baisc, only need to add complexer functions later to learning
